name: Build Draft Release

on:
  workflow_dispatch:
    inputs:
      vscode-lua-git-tag:
        description: Git tag to check out for the vscode-lua repo
        required: true
      semver:
        description: Semantic version to release
        required: true

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:

      - name: Clone the vscode-lua repository
        uses: actions/checkout@v2
        with:
          repository: sumneko/vscode-lua
          path: vscode-lua
          ref: ${{ github.event.inputs.vscode-lua-git-tag }}
          submodules: recursive

      - name: Clone the LSP-lua repository
        uses: actions/checkout@v2
        with:
          repository: sublimelsp/LSP-lua
          path: LSP-lua-source

      - name: Create the release files
        run: bash LSP-lua-source/make.sh

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.semver }}
          release_name: Release ${{ github.event.inputs.semver }}
          draft: true
          prerelease: false
          body: This release contains version ${{ github.event.inputs.vscode-lua-git-tag }} of the lua language server.

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./LSP-lua_linux-x64.zip
          asset_name: LSP-lua_linux-x64.zip
          asset_content_type: application/zip

      - name: Upload macOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./LSP-lua_osx-x64.zip
          asset_name: LSP-lua_osx-x64.zip
          asset_content_type: application/zip

      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./LSP-lua_windows-x64.zip
          asset_name: LSP-lua_windows-x64.zip
          asset_content_type: application/zip
